### ISSUE TITLE
 Seed handler does not exist

### ISSUE THREAD

**Issue by lazarote** [ticktackk/SeederForXF2#2]
Hi, im running with this error while im using the addon :(

root@localhost:/data/www/default# php cmd.php tck-seeder:seed

Running clean up tasks...

In Seed.php line 26:
 Seed handler does not exist:  
 root@localhost:/data/www/default#

**Comment by ticktackk** [comment]
How was the add-on installed?

**Comment by lazarote** [comment]
> How was the add-on installed
I pasted the src folder into my web and installed in _mywebsite/admin.php?add-ons/_

**Comment by ticktackk** [comment]
1. Uninstall the add-on
2. Follow the download link on xenforo.com
3. Install from that archive

**Comment by lazarote** [comment]
works for me (in a clean installation) but ...

Now I created a new test forum and installed the Dragonbyte shop and credit addon. Will this error be related to that?

_Stack trace:
#0 /data/www/default/src/XF/Db/Mysqli/Adapter.php(28): XF\Db\Mysqli\Adapter->makeConnection(Array)
#1 /data/www/default/src/XF/Db/AbstractAdapter.php(60): XF\Db\Mysqli\Adapter->getConnection()
#2 /data/www/default/src/XF/Db/Mysqli/Adapter.php(113): XF\Db\AbstractAdapter->connect()
#3 /data/www/default/src/XF/Db/AbstractAdapter.php(516): XF\Db\Mysqli\Adapter->escapeString('options')
#4 /data/www/default/src/XF/Db/AbstractAdapter.php(494): XF\Db\AbstractAdapter->quote('options')
#5 /data/www/default/src/XF/DataRegistry.php(138): XF\Db\AbstractAdapter->quote(Array)
#6 /data/www/default/src/XF/DataRegistry.php(83): XF\DataRegistry->readFromDb(Array, Array)
#7 /data/www/default/src/XF/DataRegistry.php(226): XF\DataRegistry->get(Array)
#8 /data/www/default/src/XF/App.php(1644): XF\DataRegistry->offsetGet('options')
#9 /data/www/default/src/XF/Container.php(28): XF\App->XF\{closure}(Object(XF\Contai in /data/www/default/src/XF/Db/Mysqli/Adapter.php on line 160
root@localhost:/data/www/default#_

**Comment by ticktackk** [comment]
I would need to see the exact error message.
